Log:
quarta-feira, 12 de junho de 2024 00:15:00
Título do log: Erro interno do servidor.
Mensagem: Ocorreu um erro interno no servidor.

Erro: erro de implementação

stackTrace:    at Taskfy.API.Services.Auth.AuthService.LoginAsync(LoginModelDTO usuarioModel)
   at Taskfy.API.Controllers.AuthController.Login(LoginModelDTO usuarioModel)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Taskfy.API.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context)

source: Taskfy.API

exception: 

-----------------------------------

Log:
quarta-feira, 12 de junho de 2024 00:20:32
Título do log: Erro interno do servidor.
Mensagem: Ocorreu um erro interno no servidor.

Erro: erro de implementação

stackTrace:    at Taskfy.API.Services.Auth.AuthService.LoginAsync(LoginModelDTO usuarioModel) in C:\Users\paulo.costa\Dev\Projetos\projetos\Taskfy\Taskfy.API\Services\Auth\AuthService.cs:line 62
   at Taskfy.API.Controllers.AuthController.Login(LoginModelDTO usuarioModel) in C:\Users\paulo.costa\Dev\Projetos\projetos\Taskfy\Taskfy.API\Controllers\AuthController.cs:line 43
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Taskfy.API.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in C:\Users\paulo.costa\Dev\Projetos\projetos\Taskfy\Taskfy.API\Middlewares\GlobalExceptionHandlerMiddleware.cs:line 20

source: Taskfy.API

exception: 

-----------------------------------

Log:
quarta-feira, 12 de junho de 2024 00:23:26
Título do log: Erro interno do servidor.
Mensagem: Ocorreu um erro interno no servidor.

Erro: erro de implementação

stackTrace:    at Taskfy.API.Services.Auth.AuthService.LoginAsync(LoginModelDTO usuarioModel) in C:\Users\paulo.costa\Dev\Projetos\projetos\Taskfy\Taskfy.API\Services\Auth\AuthService.cs:line 62
   at Taskfy.API.Controllers.AuthController.Login(LoginModelDTO usuarioModel) in C:\Users\paulo.costa\Dev\Projetos\projetos\Taskfy\Taskfy.API\Controllers\AuthController.cs:line 43
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Taskfy.API.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in C:\Users\paulo.costa\Dev\Projetos\projetos\Taskfy\Taskfy.API\Middlewares\GlobalExceptionHandlerMiddleware.cs:line 20

source: Taskfy.API

exception: 

-----------------------------------

Log:
quarta-feira, 12 de junho de 2024 00:23:37
Título do log: Erro interno do servidor.
Mensagem: Ocorreu um erro interno no servidor.

Erro: erro de implementação

stackTrace:    at Taskfy.API.Services.Auth.AuthService.LoginAsync(LoginModelDTO usuarioModel) in C:\Users\paulo.costa\Dev\Projetos\projetos\Taskfy\Taskfy.API\Services\Auth\AuthService.cs:line 62
   at Taskfy.API.Controllers.AuthController.Login(LoginModelDTO usuarioModel) in C:\Users\paulo.costa\Dev\Projetos\projetos\Taskfy\Taskfy.API\Controllers\AuthController.cs:line 43
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Taskfy.API.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in C:\Users\paulo.costa\Dev\Projetos\projetos\Taskfy\Taskfy.API\Middlewares\GlobalExceptionHandlerMiddleware.cs:line 20

source: Taskfy.API

exception: 

-----------------------------------

Log:
quarta-feira, 12 de junho de 2024 00:29:41
Título do log: Login - Sucesso
Mensagem: Login efetuado com sucesso!
-----------------------------------

Log:
quarta-feira, 12 de junho de 2024 10:34:27
Título do log: Login - Sucesso
Mensagem: Login efetuado com sucesso!
-----------------------------------

Log:
quarta-feira, 12 de junho de 2024 10:38:22
Título do log: Erro interno do servidor.
Mensagem: Ocorreu um erro interno no servidor.

Erro: erro implementação

stackTrace:    at Taskfy.API.Services.Auth.AuthService.LoginAsync(LoginModelDTO usuarioModel) in C:\Users\paulo.costa\Dev\Projetos\projetos\Taskfy\Taskfy.API\Services\Auth\AuthService.cs:line 64
   at Taskfy.API.Controllers.AuthController.Login(LoginModelDTO usuarioModel) in C:\Users\paulo.costa\Dev\Projetos\projetos\Taskfy\Taskfy.API\Controllers\AuthController.cs:line 43
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Taskfy.API.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in C:\Users\paulo.costa\Dev\Projetos\projetos\Taskfy\Taskfy.API\Middlewares\GlobalExceptionHandlerMiddleware.cs:line 20

source: Taskfy.API

exception: 

-----------------------------------

Log:
quarta-feira, 12 de junho de 2024 14:13:20
Título do log: Login - Sucesso
Mensagem: Login efetuado com sucesso!
-----------------------------------

Log:
quarta-feira, 12 de junho de 2024 14:14:00
Título do log: Login - Sucesso
Mensagem: Login efetuado com sucesso!
-----------------------------------

Log:
quarta-feira, 12 de junho de 2024 14:16:28
Título do log: Login - Sucesso
Mensagem: Login efetuado com sucesso!
-----------------------------------

